refresh_rate: 20
message_queue_size: 10
auto_arm: false
auto_offboard: false

distance_completion_threshold: 0.3
velocity_completion_threshold: 0.1
yaw_completion_threshold: 0.5
default_height: 2.0

exploration_point_of_interest_topic: ai/exploration_point_of_interest